# Form implementation generated from reading ui file 'Main_Windows.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def getTextEdit(self):
        return self.textEdit

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 681, 621))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")

        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.actionOpenDB = QtGui.QAction(MainWindow)
        self.actionOpenDB.setObjectName("actionOpenDB")
        self.menuActions.addAction(self.actionOpenDB)
        self.actionStartScanning = QtGui.QAction(MainWindow)
        self.actionStartScanning.setObjectName("actionStartScanning")
        self.menuActions.addAction(self.actionStartScanning)
        self.actionClearConsole = QtGui.QAction(MainWindow)
        self.actionClearConsole.setObjectName("actionClearConsole")
        self.menuActions.addAction(self.actionClearConsole)

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("CGIBUGScaner", "CGIBUGScaner"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.actionStartScanning.setText(_translate("MainWindow", "Start scanning"))
        self.actionClearConsole.setText(_translate("MainWindow", "Clear console"))
        self.actionOpenDB.setText(_translate("MainWindow", "Open DB"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
