# Form implementation generated from reading ui file 'bugger.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CGIBug(object):
    def setupUi(self, CGIBug):
        CGIBug.setObjectName("CGIBug")
        CGIBug.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        CGIBug.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CGIBug)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        CGIBug.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CGIBug)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        CGIBug.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CGIBug)
        self.statusbar.setObjectName("statusbar")
        CGIBug.setStatusBar(self.statusbar)
        self.actionOpenDB = QtGui.QAction(CGIBug)
        self.actionOpenDB.setObjectName("actionOpenDB")
        self.actionStartScanning = QtGui.QAction(CGIBug)
        self.actionStartScanning.setObjectName("actionStartScanning")
        self.actionClearConsole = QtGui.QAction(CGIBug)
        self.actionClearConsole.setObjectName("actionClearConsole")
        self.menuActions.addAction(self.actionOpenDB)
        self.menuActions.addAction(self.actionStartScanning)
        self.menuActions.addAction(self.actionClearConsole)
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(CGIBug)
        QtCore.QMetaObject.connectSlotsByName(CGIBug)

    def retranslateUi(self, CGIBug):
        _translate = QtCore.QCoreApplication.translate
        CGIBug.setWindowTitle(_translate("CGIBug", "CGI Bugger"))
        self.menuActions.setTitle(_translate("CGIBug", "Actions"))
        self.actionOpenDB.setText(_translate("CGIBug", "Open DB"))
        self.actionStartScanning.setText(_translate("CGIBug", "Start scanning"))
        self.actionClearConsole.setText(_translate("CGIBug", "Clear console"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CGIBug = QtWidgets.QMainWindow()
    ui = Ui_CGIBug()
    ui.setupUi(CGIBug)
    CGIBug.show()
    sys.exit(app.exec())
